databases:
  - name: budgetapp
    databaseName: budget_app_w2n3
    user: postgress

services:
  - type: web
    name: budgetapp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars: 
      - fromGroup: staging
      - key: DATABASE_URL
        fromDatabase:
        name: budgetapp
        property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
